name: "Hit a webhook"
 
on:
  workflow_dispatch:
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
    - env:
        GH_TOKEN: ${{ secrets.TOKEN }}
      run: |
         gh api \
         -H "Accept: application/vnd.github+json" \
         -H "X-GitHub-Api-Version: 2022-11-28" \
         /user/following/sagars729
